spring:
  application:
    name: spring-ai-web

  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-haiku-4-5

    mcp:
      client:
        initialized: false
        streamable-http:
          connections:
            spring-ai-mcp:
              url: http://localhost:8081

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
